### ISSUE TITLE
Regression Model Summary | Print Regression Model summary

### ISSUE THREAD

**Issue by rkthakur** [rkthakur/mediamixmodeling#4]
Regression Model Summary should be displayed in a section below the Media mix model pi chart in following format :
# OLS Regression Results

<img width="682" alt="ttt" src="https://cloud.githubusercontent.com/assets/3679045/18224432/67b8fe12-71f2-11e6-8488-6190fd6b10c9.png">
All required data is published under "/api/modeldata" in "summary" object

**Comment by abhishek-net** [comment]
Done.
