### ISSUE TITLE
Login/Registration | User should be able to login and register 

### ISSUE THREAD

**Issue by rkthakur** [rkthakur/mediamixmodeling#5]
User should be able to login and register preferably through social media. Use any lightweight node.js module.

**Comment by abhishek-net** [comment]
Facebook login implemented, check the commit abhishek-net@643315c1cefc26ecb5c88b7267a5f862ccf49a4d

**Comment by RupeshThakur11** [comment]
Actually I was designing login and registration part in Python /nodejs
